whoeven99/SpringBackend

pom.xml
Reverts whoeven99/SpringBackend#13
=> Revert "Update"

pom.xml, src/main/java/com/bogdatech/controller/TestController.java, src/main/resources/application.properties
Reverts whoeven99/SpringBackend#12
=> Revert "Update Sql"

pom.xml, src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/integration/ShopifyHttpIntegration.java, src/main/java/com/bogdatech/logic/CurrencyService.java, src/main/java/com/bogdatech/model/controller/request/ShopifyRequest.java, src/main/java/com/bogdatech/query/TestQuery.java
=> 修改添加货币的实现逻辑

src/main/java/com/bogdatech/integration/ShopifyHttpIntegration.java, src/main/java/com/bogdatech/logic/CurrencyService.java
=> 修改删除货币的实现逻辑

src/main/java/com/bogdatech/controller/CurrencyController.java, src/main/java/com/bogdatech/enums/ErrorEnum.java, src/main/java/com/bogdatech/logic/CurrencyService.java, src/main/java/com/bogdatech/task/RateTask.java
=> 将货币的CRUD逻辑全部重新实现

pom.xml, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/integration/ShopifyHttpIntegration.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/model/controller/request/TranslateRequest.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/resources/application.properties
=> Translate product

src/main/java/com/bogdatech/logic/TranslateService.java
=> 连接谷歌翻译接口测试2

src/main/java/com/bogdatech/logic/TranslateService.java, src/main/resources/application.properties
=> 连接谷歌翻译接口测试3,用发送curl请求

src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/model/controller/request/TranslateRequest.java
测试环境下可以连接谷歌翻译API，但本地环境下一直报 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
=> 测试环境下可以连接谷歌翻译API，但本地环境下一直报 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/integration/ShopifyHttpIntegration.java, src/main/java/com/bogdatech/logic/CurrencyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/query/ShopifyQuery.java, src/main/java/com/bogdatech/repository/JdbcRepository.java
2，将调用外部api的逻辑，挪到Integration里面去
=> 1，将sql相关操作移到repository里面

src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/integration/TranslateApiIntegration.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/StringUtil.java, src/main/resources/jsonData/produck.json, src/main/resources/jsonData/project.json
=> 1，修改谷歌翻译API的调用

src/main/java/com/bogdatech/entity/TranslateResourceDTO.java, src/main/java/com/bogdatech/integration/ShopifyHttpIntegration.java, src/main/java/com/bogdatech/integration/TranslateApiIntegration.java
2，在translationResources增加了一条DELIVERY_METHOD_DEFINITION类型数据
=> 1,修改谷歌翻译的返回值类型

pom.xml, src/main/java/com/bogdatech/logic/TranslateService.java
=> 1,添加pom.xml

src/main/java/com/bogdatech/Application.java, src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/integration/TestingEnvironmentIntegration.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java
=> 1,封装调用shopify接口，测试该接口是否可用

src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/entity/TranslateResourceDTO.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/model/controller/request/TranslationCounterRequest.java, src/main/java/com/bogdatech/query/ShopifyQuery.java, src/main/java/com/bogdatech/repository/JdbcRepository.java, src/main/java/com/bogdatech/utils/CamelToUnderscore.java, src/main/java/com/bogdatech/utils/TypeConversionUtils.java
2，产品要求重新翻译一下products和主题，测试翻译质量
=> 1,实现了获取用户状态的方法

src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/controller/UserController.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/UserService.java, src/main/java/com/bogdatech/model/controller/request/UserRequest.java, src/main/java/com/bogdatech/model/controller/request/UserSubscriptionsRequest.java, src/main/java/com/bogdatech/model/controller/response/BaseResponse.java, src/main/java/com/bogdatech/repository/JdbcRepository.java
=> 1,修改添加到数据库的sql语句

src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/entity/TranslateResourceDTO.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java
=> 1,修改翻译功能计数器的位置，翻译所有文件

pom.xml, src/main/java/com/bogdatech/Service/ICharsOrdersService.java, src/main/java/com/bogdatech/Service/ITranslateTextService.java, src/main/java/com/bogdatech/Service/impl/CharsOrdersServiceImpl.java, src/main/java/com/bogdatech/Service/impl/TranslateTextServiceImpl.java, src/main/java/com/bogdatech/Service/impl/TranslationCounterServiceImpl.java, src/main/java/com/bogdatech/constants/TranslateConstants.java, src/main/java/com/bogdatech/controller/CharsOrdersController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/controller/TranslationCounterController.java, src/main/java/com/bogdatech/entity/CharsOrdersDO.java, src/main/java/com/bogdatech/entity/TranslateResourceDTO.java, src/main/java/com/bogdatech/entity/TranslateTextDO.java, src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/logic/OrderService.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/mapper/CharsOrdersMapper.java, src/main/java/com/bogdatech/mapper/TranslateTextMapper.java, src/main/java/com/bogdatech/mapper/TranslationCounterMapper.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/StringUtils.java, src/main/resources/application.properties
=> 1,添加修改获取订单信息

src/main/java/com/bogdatech/Application.java, src/main/java/com/bogdatech/Service/ITranslationCounterService.java, src/main/java/com/bogdatech/Service/impl/TranslationCounterServiceImpl.java, src/main/java/com/bogdatech/controller/TranslationCounterController.java, src/main/java/com/bogdatech/mapper/TranslationCounterMapper.java
=> 1,测试能否拿到ALIBABA_CLOUD_ACCESS_KEY_ID数据

src/main/java/com/bogdatech/Service/ISubscriptionProjectService.java, src/main/java/com/bogdatech/Service/impl/SubscriptionProjectServiceImpl.java, src/main/java/com/bogdatech/controller/SubscriptionProjectController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/entity/SubscriptionProjectDO.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/mapper/SubscriptionProjectMapper.java
=> 1,默认给用户计划设为免费计划

src/main/java/com/bogdatech/Service/impl/TranslateTextServiceImpl.java, src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/integration/TranslateApiIntegration.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java
=> 1，对谷歌语言添加model：base

pom.xml, src/main/java/com/bogdatech/config/WebConfig.java, src/main/java/com/bogdatech/controller/CurrencyController.java, src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/enums/ErrorEnum.java, src/main/java/com/bogdatech/integration/ShopifyHttpIntegration.java, src/main/java/com/bogdatech/logic/CurrencyService.java, src/main/java/com/bogdatech/logic/RateDataService.java, src/main/java/com/bogdatech/model/controller/request/CurrencyRequest.java, src/main/java/com/bogdatech/model/controller/request/ShopifyRequest.java, src/main/java/com/bogdatech/query/TestQuery.java, src/main/java/com/bogdatech/task/RateTask.java
根据前端的要求，修改了增删改功能的实现逻辑，新增了查询功能，（前端测过没问题）
=> Add currency

pom.xml, src/main/java/com/bogdatech/Application.java, src/main/java/com/bogdatech/Service/impl/CurrenciesServiceImpl.java, src/main/java/com/bogdatech/config/MybatisPlusConfig.java, src/main/java/com/bogdatech/mapper/CurrenciesMapper.java, src/main/resources/application.properties
=> 1,修改插入货币功能，返回货币信息

src/main/java/com/bogdatech/Service/ICurrenciesService.java, src/main/java/com/bogdatech/Service/impl/CurrenciesServiceImpl.java, src/main/java/com/bogdatech/config/CurrencyConfig.java, src/main/java/com/bogdatech/controller/CurrencyController.java, src/main/java/com/bogdatech/mapper/CurrenciesMapper.java, src/main/java/com/bogdatech/model/controller/request/CurrencyRequest.java
=> 1,修改获取货币及符号功能

src/main/java/com/bogdatech/Service/IGlossaryService.java, src/main/java/com/bogdatech/Service/impl/GlossaryServiceImpl.java, src/main/java/com/bogdatech/Service/impl/UserSubscriptionsServiceImpl.java, src/main/java/com/bogdatech/constants/TranslateConstants.java, src/main/java/com/bogdatech/controller/GlossaryController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/controller/UserController.java, src/main/java/com/bogdatech/logic/GlossaryService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/logic/UserService.java, src/main/java/com/bogdatech/utils/CaseSensitiveUtils.java
=> 1,按前端要求修改/user/add的返回值

src/main/java/com/bogdatech/Service/IAILanguagePacksService.java, src/main/java/com/bogdatech/Service/IKlaviyoDataService.java, src/main/java/com/bogdatech/Service/impl/AILanguagePacksServiceImpl.java, src/main/java/com/bogdatech/Service/impl/KlaviyoDataServiceImpl.java, src/main/java/com/bogdatech/constants/TranslateConstants.java, src/main/java/com/bogdatech/context/TranslateContext.java, src/main/java/com/bogdatech/controller/GlossaryController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/entity/KlaviyoDataDO.java, src/main/java/com/bogdatech/entity/TranslateResourceDTO.java, src/main/java/com/bogdatech/integration/ChatGptIntegration.java, src/main/java/com/bogdatech/integration/TranslateApiIntegration.java, src/main/java/com/bogdatech/logic/AILanguagePackService.java, src/main/java/com/bogdatech/logic/KlaviyoService.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/mapper/AILanguagePacksMapper.java, src/main/java/com/bogdatech/mapper/KlaviyoDataMapper.java, src/main/java/com/bogdatech/model/controller/request/UserAddRequest.java, src/main/java/com/bogdatech/model/controller/request/UserGetRequest.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/StringUtils.java
=>  1,放开测试范围，测试AI翻译质量

src/main/java/com/bogdatech/Service/IAILanguagePacksService.java, src/main/java/com/bogdatech/Service/impl/AILanguagePacksServiceImpl.java, src/main/java/com/bogdatech/context/TranslateContext.java, src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/entity/AILanguagePacksDO.java, src/main/java/com/bogdatech/logic/AILanguagePackService.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/mapper/AILanguagePacksMapper.java, src/main/java/com/bogdatech/utils/CalculateTokenUtils.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/StringUtils.java
1,修改对提示词的处理方法，对其中的{{apparel}}，{{Chinese}}，{{product}}进行处理
2，增加语言包的倍率功能，对不同语言包有不同的倍率计算
=> 增加处理提示词和增加倍率的功能

src/main/java/com/bogdatech/Service/ICurrenciesService.java, src/main/java/com/bogdatech/Service/ITranslatesService.java, src/main/java/com/bogdatech/Service/ITranslationCounterService.java, src/main/java/com/bogdatech/Service/impl/CurrenciesServiceImpl.java, src/main/java/com/bogdatech/Service/impl/TranslatesServiceImpl.java, src/main/java/com/bogdatech/Service/impl/TranslationCounterServiceImpl.java, src/main/java/com/bogdatech/config/WebConfig.java, src/main/java/com/bogdatech/controller/AILanguagePacksController.java, src/main/java/com/bogdatech/controller/CharsOrdersController.java, src/main/java/com/bogdatech/controller/CurrencyController.java, src/main/java/com/bogdatech/controller/GlossaryController.java, src/main/java/com/bogdatech/controller/KlaviyoController.java, src/main/java/com/bogdatech/controller/PurchaseController.java, src/main/java/com/bogdatech/controller/RateController.java, src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/controller/SubscriptionProjectController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/controller/TranslationCounterController.java, src/main/java/com/bogdatech/controller/UserController.java, src/main/java/com/bogdatech/logic/PurchaseService.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/model/controller/request/CurrencyRequest.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 1,修改url和请求方式

src/main/java/com/bogdatech/controller/CurrencyController.java, src/main/java/com/bogdatech/entity/CurrenciesDO.java, src/main/java/com/bogdatech/integration/TestingEnvironmentIntegration.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/task/RateTask.java
1,添加primaryStatus
2，修改请求shopify的url
=> 1,添加primaryStatus

src/main/java/com/bogdatech/Service/ICurrenciesService.java, src/main/java/com/bogdatech/Service/impl/CurrenciesServiceImpl.java, src/main/java/com/bogdatech/controller/CurrencyController.java, src/main/java/com/bogdatech/integration/ChatGptIntegration.java, src/main/java/com/bogdatech/logic/PurchaseService.java, src/main/java/com/bogdatech/logic/RateDataService.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/mapper/CurrenciesMapper.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
1,实现初始化方法（initCurrency）： 判断数据库中shopName是否有默认语言，有的话返回对应信息，没有的话返回空。 
2,修改getCacheData方法，添加功能：判断primaryStatus是否为0且exchangeRate是否为Auto，如果是，从缓存中获取对应货币代码汇率，并做处理，获得对应汇率；如果不是直接返回对应货币信息。
3,对翻译做修改，40以上是AI翻译，40一下用谷歌翻译翻译
=> 修改货币功能和翻译方式

src/main/java/com/bogdatech/controller/AILanguagePacksController.java, src/main/java/com/bogdatech/controller/CharsOrdersController.java, src/main/java/com/bogdatech/controller/CurrencyController.java, src/main/java/com/bogdatech/controller/GlossaryController.java, src/main/java/com/bogdatech/controller/KlaviyoController.java, src/main/java/com/bogdatech/controller/PurchaseController.java, src/main/java/com/bogdatech/controller/RateController.java, src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/controller/SubscriptionProjectController.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/controller/TranslationCounterController.java, src/main/java/com/bogdatech/controller/UserController.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 修改@Auto的方式和将微软翻译改为谷歌翻译i

src/main/java/com/bogdatech/Service/ICurrenciesService.java, src/main/java/com/bogdatech/Service/impl/CurrenciesServiceImpl.java, src/main/java/com/bogdatech/controller/CurrencyController.java, src/main/java/com/bogdatech/logic/TranslateService.java
=> 1,修改更新默认货币的方法

src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/mapper/CurrenciesMapper.java, src/main/java/com/bogdatech/task/RateTask.java
1,修改获取货币信息的返回值：添加primaryStatus字段
=> 1,修改获取货币信息的返回值：添加primaryStatus字段

src/main/java/com/bogdatech/Service/IAILanguagePacksService.java, src/main/java/com/bogdatech/Service/impl/AILanguagePacksServiceImpl.java, src/main/java/com/bogdatech/Service/impl/CurrenciesServiceImpl.java, src/main/java/com/bogdatech/controller/AILanguagePacksController.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/MapUtils.java
1,修改getCurrencyByShopName,返回值中添加symbol字段。修改获取symbol的方法
2,修改addDefaultAILanguage方法添加判断是否shopName存在，将返回值改为void
=> 修改getCurrencyByShopName和addDefaultAILanguage方法

src/main/java/com/bogdatech/constants/TranslateConstants.java, src/main/java/com/bogdatech/entity/TranslateResourceDTO.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
1,修改AI翻译使用范围（product，blog）
2，优化翻译判断逻辑
=> 1,修改AI翻译使用范围（product，blog）

src/main/java/com/bogdatech/Service/IRightsAndInterestsService.java, src/main/java/com/bogdatech/Service/IUsersService.java, src/main/java/com/bogdatech/Service/impl/RightsAndInterestsImpl.java, src/main/java/com/bogdatech/controller/RightsAndInterestController.java, src/main/java/com/bogdatech/entity/RightsAndInterestsDO.java, src/main/java/com/bogdatech/entity/UserRightsAndInterestsDO.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/mapper/RightsAndInterestsMapper.java, src/main/java/com/bogdatech/model/controller/request/UserRAIRequest.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
1,修改html的翻译逻辑
2，实现读取权益表所有的权功能
3，实现创建用户对应的权益的功能
=> 修改html的翻译逻辑和实现权益表的读写功能

src/main/java/com/bogdatech/Service/impl/AILanguagePacksServiceImpl.java, src/main/java/com/bogdatech/constants/MailChimpConstants.java, src/main/java/com/bogdatech/controller/EmailController.java, src/main/java/com/bogdatech/controller/TranslationCounterController.java, src/main/java/com/bogdatech/entity/UsersDO.java, src/main/java/com/bogdatech/integration/EmailIntegration.java, src/main/java/com/bogdatech/logic/MailChimpService.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/UserService.java, src/main/java/com/bogdatech/mapper/AILanguagePacksMapper.java, src/main/java/com/bogdatech/model/controller/request/SendEmailRequest.java, src/main/java/com/bogdatech/model/controller/request/TranslateSuccessRequest.java, src/main/java/com/bogdatech/requestBody/EmailRequestBody.java, src/main/resources/application.properties
1,实现用postMan给用户发送邮件（由于目前使用的是免费计划，所以只能发送给同域的用户，如：example.ciwi.ai）
2，将https://mandrillapp.com/api/1.0/messages/send-template封装成一个sendEmail静态方法，实现5个静态方法（sendFirstInstallMail等）存放模板各需要的变量（不同模板的变量不同），调用sendEmail发送邮件。
3，修改用户服务的功能
=> 实现邮件功能和修改用户服务

src/main/java/com/bogdatech/Service/ITranslationCounterService.java, src/main/java/com/bogdatech/Service/impl/TranslationCounterServiceImpl.java, src/main/java/com/bogdatech/controller/EmailController.java, src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/controller/UserController.java, src/main/java/com/bogdatech/integration/EmailIntegration.java, src/main/java/com/bogdatech/logic/MailChimpService.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/UserService.java
1,实现一个方法判断是否初始化完，再将判断方法以Map<String,Boolean>的形式返回
2,修改发送邮件的功能
=> 1,实现一个方法判断是否初始化完，再将判断方法以Map<String,Boolean>的形式返回

src/main/java/com/bogdatech/controller/EmailController.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/controller/UserController.java, src/main/java/com/bogdatech/logic/MailChimpService.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TestService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/requestBody/EmailRequestBody.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/utils/CalculateTokenUtils.java
=> 1，对应网站卸载后停止翻译app

src/main/java/com/bogdatech/Service/ITranslatesService.java, src/main/java/com/bogdatech/Service/impl/TranslatesServiceImpl.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/controller/UserController.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/mapper/TranslatesMapper.java, src/main/java/com/bogdatech/model/controller/request/TargetListRequest.java
1，细化卸载后停止翻译效果，将status变为3
2,将list形式的target存入数据库
=> 细化卸载后停止翻译，将list形式的target存入数据库

src/main/java/com/bogdatech/Service/ITranslatesService.java, src/main/java/com/bogdatech/Service/impl/TranslatesServiceImpl.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/controller/UserController.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/mapper/TranslatesMapper.java
1，在master分支的基础上添加终止翻译的功能，用于用户卸载后终止翻译，并将翻译状态改为部分翻译
=> 在master分支的基础上添加终止翻译的功能

src/main/java/com/bogdatech/entity/TranslateResourceDTO.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 1，修改microsoftTranslate改为谷歌的

src/main/java/com/bogdatech/Service/ITranslatesService.java, src/main/java/com/bogdatech/Service/impl/AILanguagePacksServiceImpl.java, src/main/java/com/bogdatech/Service/impl/TranslatesServiceImpl.java, src/main/java/com/bogdatech/entity/TranslateResourceDTO.java, src/main/java/com/bogdatech/integration/ShopifyHttpIntegration.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 修改修改addDefaultLanguagePack方法

src/main/java/com/bogdatech/config/LanguageFlagConfig.java, src/main/java/com/bogdatech/controller/CharsOrdersController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/integration/EmailIntegration.java, src/main/java/com/bogdatech/logic/OrderService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/logic/UserService.java, src/main/java/com/bogdatech/mapper/UsersMapper.java, src/main/java/com/bogdatech/model/controller/request/PurchaseSuccessRequest.java, src/main/java/com/bogdatech/task/RateTask.java
1,实现在用户翻译完成后发送邮件
2，实现在用户在购买字符后发送邮件
3，放开定时任务
4，将翻译范围放开
=> 实现其他两种发送邮件，修改部分数据

src/main/java/com/bogdatech/Service/IEmailService.java, src/main/java/com/bogdatech/Service/impl/EmailServiceImpl.java, src/main/java/com/bogdatech/constants/MailChimpConstants.java, src/main/java/com/bogdatech/constants/TranslateConstants.java, src/main/java/com/bogdatech/controller/EmailController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/entity/EmailDO.java, src/main/java/com/bogdatech/logic/OrderService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/logic/UserService.java, src/main/java/com/bogdatech/mapper/EmailMapper.java, src/main/java/com/bogdatech/mapper/UsersMapper.java
1,完成翻译失败的邮件发送
2，完成在翻译流程中嵌入邮件发送的功能
3，对异步的翻译方法的异常进行处理
4,实现手动停止当前的翻译
=> 邮件发送和手动停止翻译

src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/logic/UserService.java
=> 1,修改成功发送邮件的位置

src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/integration/TestingEnvironmentIntegration.java, src/main/java/com/bogdatech/integration/TranslateApiIntegration.java, src/main/java/com/bogdatech/logic/OrderService.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/model/controller/request/PurchaseSuccessRequest.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/StringUtils.java
1,修改对获取shopify本地的异常处理，加重试机制
2,修改邮件的数据，加上千分位，费用保留两位小数
3，在统计数量时，添加word计算
4，对谷歌翻译做处理，当有不再谷歌翻译范围内的语言代码时改用AI翻译（部分完成）
=> 处理异常，合并邮件服务

src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 1，修改openAI关于html的翻译

src/main/java/com/bogdatech/integration/TranslateApiIntegration.java, src/main/java/com/bogdatech/logic/TranslateService.java
=> 1,对打印的错误信息做处理

src/main/java/com/bogdatech/logic/TranslateService.java
1,在startTranslation方法里面，不抛异常改为return，打印异常信息。
=> 1,在startTranslation方法里面，不抛异常改为return，打印异常信息。

src/main/java/com/bogdatech/logic/TranslateService.java
1,修改对从数据库获取数据的处理
2，对最后失败的翻译只发一个邮件
=> 修改对从数据库获取数据的处理

src/main/java/com/bogdatech/integration/EmailIntegration.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/mapper/EmailMapper.java
=> 修改存储邮件sql语句和打印异常信息

src/main/java/com/bogdatech/Service/ITranslatesService.java, src/main/java/com/bogdatech/Service/impl/TranslatesServiceImpl.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/enums/ErrorEnum.java, src/main/java/com/bogdatech/mapper/TranslatesMapper.java
1,添加data limit的错误 2，在翻译功能里面添加一个判断，如果翻译数超过两个则报错。
=> 1,添加data limit的错误

src/main/java/com/bogdatech/controller/TestController.java
=> 1,手动添加一个获取汇率的方法

src/main/java/com/bogdatech/controller/TranslateController.java
=> 1,将翻译的数量判断注释掉

src/main/java/com/bogdatech/config/WebConfig.java
=> 1，不禁用静态资源路径

src/main/java/com/bogdatech/controller/UserController.java
=> 1，用户卸载功能什么都不做

src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/resources/application.properties
=> 禁用静态资源路径，修改获取字符逻辑，

src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/integration/ShopifyHttpIntegration.java, src/main/java/com/bogdatech/integration/TranslateApiIntegration.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/task/TranslateTask.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/resources/application.properties
1，当在test和prod环境下调用shopifyAPI和googleAPI的情况下，不再调用封装后的API。减少一层调用
2，添加一些注释，用于测试
3，完善特定的异常处理，如调用shopify的
=> 减少调用，添加注释，异常处理

src/main/java/com/bogdatech/logic/TranslateService.java
=> 1,修改翻译流程，如果包含相对路径就跳过

src/main/java/com/bogdatech/Service/impl/UserIPSwitchServiceImpl.java, src/main/java/com/bogdatech/controller/UserIPSwitchController.java, src/main/java/com/bogdatech/mapper/UserIPSwitchMapper.java
=> 修改insertSwitch方法,包含更新的问题

src/main/java/com/bogdatech/controller/UserIPSwitchController.java
=> 1,修改insertSwitch的返回值，给什么，传什么

src/main/java/com/bogdatech/logic/TranslateService.java
1,修改判断路劲的方法,当type为FILE_REFERENCE，URL，LINK，LIST_FILE_REFERENCE，LIST_LINK，LIST_URL时都不翻译，跳过
=> 判断type是否跳过路径

src/main/java/com/bogdatech/Service/ITranslatesService.java, src/main/java/com/bogdatech/Service/impl/TranslatesServiceImpl.java, src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/mapper/TranslatesMapper.java
1，修改readInfoByShopName获取方法，添加source字段
2，添加对数据库数据处理的判断条件
=> 修改readInfoByShopName获取方法，添加source字段，添加对数据库数据处理的判断条件

pom.xml, src/main/java/com/bogdatech/Service/ITranslatesService.java, src/main/java/com/bogdatech/Service/impl/TranslatesServiceImpl.java, src/main/java/com/bogdatech/constants/TranslateConstants.java, src/main/java/com/bogdatech/context/TranslateContext.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/entity/TranslatesDO.java, src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/mapper/TranslatesMapper.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
1，修改翻译逻辑
2，添加通义的API调用
3，添加resourceType供前端进度条显示
=> 修改翻译逻辑和添加通义的API调用

src/main/java/com/bogdatech/integration/ChatGptIntegration.java
=> 修改gpt的异常处理

pom.xml, src/main/java/com/bogdatech/Service/ITranslatesService.java, src/main/java/com/bogdatech/Service/impl/TranslatesServiceImpl.java, src/main/java/com/bogdatech/Service/impl/VocabularyServiceImpl.java, src/main/java/com/bogdatech/constants/TranslateConstants.java, src/main/java/com/bogdatech/context/TranslateContext.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/entity/TranslatesDO.java, src/main/java/com/bogdatech/exception/UserHandleException.java, src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/integration/ChatGptIntegration.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/mapper/TranslatesMapper.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 添加状态4 修改之前的一些问题

src/main/java/com/bogdatech/logic/TranslateService.java
1，放开tast任务
2，删除多余注释
3，修改capitalize的判断条件
=> 放开tast删除多余注释

src/main/java/com/bogdatech/Service/impl/VocabularyServiceImpl.java, src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/integration/RateHttpIntegration.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/task/RateTask.java
1,删除多余代码注释和添加合适的注释
2,添加无感知手动停止翻译的方法
3,修改手动存一条数据到shopify
=> 删除注释，添加手动停止翻译， 修改手动存一条数据

src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/exception/UserHandleException.java, src/main/java/com/bogdatech/integration/ShopifyHttpIntegration.java, src/main/java/com/bogdatech/logic/ShopifyService.java
=> 新增方法一次存储多条数据

src/main/java/com/bogdatech/Service/impl/VocabularyServiceImpl.java, src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/exception/UserHandleException.java, src/main/java/com/bogdatech/integration/RateHttpIntegration.java, src/main/java/com/bogdatech/integration/ShopifyHttpIntegration.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/task/RateTask.java
=> 实现一次插入多条数据

src/main/java/com/bogdatech/Service/impl/VocabularyServiceImpl.java, src/main/java/com/bogdatech/constants/TranslateConstants.java, src/main/java/com/bogdatech/context/TranslateContext.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/exception/UserHandleException.java, src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/logic/VocabularyService.java, src/main/java/com/bogdatech/model/controller/request/RegisterHtmlTransactionRequest.java, src/main/java/com/bogdatech/utils/SwitchModelUtils.java, src/main/java/com/bogdatech/utils/TypeConversionUtils.java, src/main/java/com/bogdatech/utils/ValueWrapper.java
=> 实现token计数，实现百炼API接口调用翻译

src/main/java/com/bogdatech/constants/TranslateConstants.java, src/main/java/com/bogdatech/context/TranslateContext.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/SwitchModelUtils.java, src/main/java/com/bogdatech/utils/ValueWrapper.java
=> 修改合并test后的报错

pom.xml, src/main/java/com/bogdatech/Service/impl/VocabularyServiceImpl.java, src/main/java/com/bogdatech/constants/TranslateConstants.java, src/main/java/com/bogdatech/context/TranslateContext.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/exception/UserHandleException.java, src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/logic/VocabularyService.java, src/main/java/com/bogdatech/model/controller/request/RegisterHtmlTransactionRequest.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/SwitchModelUtils.java, src/main/java/com/bogdatech/utils/TypeConversionUtils.java, src/main/java/com/bogdatech/utils/ValueWrapper.java
1，解决日志冲突问题
2，修改百炼的API key
3，修改一些问题
=> 将gpt改为百炼API

src/main/java/com/bogdatech/Service/IUserTypeTokenService.java, src/main/java/com/bogdatech/Service/IUsersService.java, src/main/java/com/bogdatech/Service/impl/UserServiceImpl.java, src/main/java/com/bogdatech/Service/impl/UserTypeTokenImpl.java, src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/controller/UserController.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/logic/UserService.java, src/main/java/com/bogdatech/mapper/UserTypeTokenMapper.java, src/main/java/com/bogdatech/mapper/UsersMapper.java
=> 修改stutas为2的判断

src/main/java/com/bogdatech/Service/IUserTypeTokenService.java, src/main/java/com/bogdatech/Service/impl/UserTypeTokenImpl.java, src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/controller/UserTypeTokenController.java, src/main/java/com/bogdatech/entity/TranslateResourceDTO.java, src/main/java/com/bogdatech/entity/UserTypeTokenDO.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/logic/UserTypeTokenService.java, src/main/java/com/bogdatech/mapper/UserTypeTokenMapper.java, src/main/java/com/bogdatech/model/controller/request/ClickTranslateRequest.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/utils/TypeConversionUtils.java
一开始获取一下初始值，后面翻译完后，更新对应语言的token
=> 一开始获取一下初始值，后面翻译完后，更新对应语言的token

src/main/java/com/bogdatech/Service/impl/UserTypeTokenImpl.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/logic/UserTypeTokenService.java
=> 修改翻译完获取token的位置

src/main/java/com/bogdatech/logic/OrderService.java, src/main/java/com/bogdatech/logic/TranslateService.java
=> 1,给邮件添加注释,修改邮件

src/main/java/com/bogdatech/Service/IVocabularyService.java, src/main/java/com/bogdatech/Service/impl/TranslatesServiceImpl.java, src/main/java/com/bogdatech/Service/impl/VocabularyServiceImpl.java, src/main/java/com/bogdatech/constants/TranslateConstants.java, src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/controller/UserController.java, src/main/java/com/bogdatech/controller/VocabularyController.java, src/main/java/com/bogdatech/entity/TranslateTextDO.java, src/main/java/com/bogdatech/entity/VocabularyDO.java, src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/logic/VocabularyService.java, src/main/java/com/bogdatech/mapper/TranslatesMapper.java, src/main/java/com/bogdatech/utils/ApiCodeUtils.java, src/main/java/com/bogdatech/utils/CalculateTokenUtils.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/PlaceholderUtils.java
1,修改词汇表方法
2，修改翻译逻辑的API调用方法，部分语言代码改为用qwen-mt的方法
3，修改翻译逻辑中google的计数规则
4，修改对{{ product.value }}  %{product.value}  {{xx[x].xx}} {%product.value%}的翻译逻辑
=> 主要修改方法是用qwen-mt代替部分google，另外修改词汇表的方法

src/main/java/com/bogdatech/Service/ITranslatesService.java, src/main/java/com/bogdatech/Service/impl/TranslatesServiceImpl.java, src/main/java/com/bogdatech/controller/TranslateController.java
1,修改原readTranslateDOByArray方法至原来的方法
2，实现getTranslateDOByShopNameAndSource方法，获取最新时间的翻译项数据
=> 修改原readTranslateDOByArray方法至原来的方法，新增getTranslateDOByShopNameAndSource方法获取最新时间的翻译项数据

src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java
=> 1,修改html的翻译逻辑

src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java
1,修改html的翻译逻辑，对于特殊空白文本做处理，直接拼接
=> 1,修改html的翻译逻辑，对于特殊空白文本做处理，直接拼接

src/main/java/com/bogdatech/controller/PrivateKeyController.java, src/main/java/com/bogdatech/integration/TranslateApiIntegration.java, src/main/java/com/bogdatech/logic/PrivateKeyService.java
=> 1,修改google调用方法

src/main/java/com/bogdatech/integration/TranslateApiIntegration.java, src/main/java/com/bogdatech/logic/TranslateService.java
=> 1,修改存储数据库的问题

src/main/java/com/bogdatech/Service/impl/VocabularyServiceImpl.java
=> 1,修改存入数据库判断逻辑

src/main/java/com/bogdatech/Service/impl/VocabularyServiceImpl.java, src/main/java/com/bogdatech/entity/TranslateTextDO.java, src/main/java/com/bogdatech/logic/TranslateService.java
=> 修改线程池和覆盖翻译

src/main/java/com/bogdatech/config/AzureKeyVaultConfig.java, src/main/java/com/bogdatech/controller/PrivateKeyController.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/integration/PrivateIntegration.java, src/main/java/com/bogdatech/logic/PrivateKeyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/logic/UserPrivateService.java
1,修改获取Azure值的方法
2，修改私有key的翻译流程
=> 修改获取Azure值的方法 .修改私有key的翻译流程

pom.xml, src/main/java/com/bogdatech/config/AzureKeyVaultConfig.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java
=> 修改编码问题和修改secret调用方法

src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/integration/EmailIntegration.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java
=> 修改编码问题和发送邮件的方法

src/main/java/com/bogdatech/logic/PrivateKeyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 修改编码问题和修改成功翻译发送邮件的方法

src/main/java/com/bogdatech/Service/IUserPrivateService.java, src/main/java/com/bogdatech/Service/impl/UserPrivateServiceImpl.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/controller/UserPrivateController.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/logic/UserPrivateService.java, src/main/java/com/bogdatech/mapper/UserPrivateMapper.java, src/main/java/com/bogdatech/task/RateTask.java
=> 增加删除的方法和修改翻译对HTML实体的修改

src/main/java/com/bogdatech/logic/UserPrivateService.java
=> 修改getUserdata的返回值

src/main/java/com/bogdatech/logic/TranslateService.java
=> 解开普通翻译邮件发送

src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/ResourceTypeUtils.java
=> 1，优化硬编码和邮件功能

src/main/java/com/bogdatech/logic/PrivateKeyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java
1，修改私有key的词汇表翻译
2，修改成功和失败邮件的发送
=> 修改私有key的词汇表翻译和修改成功和失败邮件的发送

src/main/java/com/bogdatech/logic/PrivateKeyService.java
=> 1,修改部分翻译的发送邮件

src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/PrintUtils.java
=> 1,发布到test，测试一下打印效果

src/main/java/com/bogdatech/logic/PrivateKeyService.java
1,私有key也打印翻译信息，发布到test，测试一下打印效果
=> 私有key也打印翻译信息，发布到test，测试一下打印效果

src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/utils/PrintUtils.java
=> 解开定时任务，修改打印逻辑，添加注释

src/main/java/com/bogdatech/logic/TranslateService.java
=> 修改对value的判断

src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java, src/main/java/com/bogdatech/utils/PlaceholderUtils.java
1,修改Google翻译逻辑，如果有变量，进行处理不翻译。
2,修改glossary的html翻译逻辑。
=> 修改Google翻译逻辑，修改glossary的html逻辑

src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/CaseSensitiveUtils.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 打印glossary日志

src/main/java/com/bogdatech/utils/CaseSensitiveUtils.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 1,打印glossary日志

src/main/java/com/bogdatech/logic/PrivateKeyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/CaseSensitiveUtils.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 1,根据source选择怎么匹配

src/main/java/com/bogdatech/utils/CaseSensitiveUtils.java
1,替换后的文本是否和替换前的文本一致，如果一致，换一种替换方法；如果不一致，输出
=> 替换后的文本是否和替换前的文本一致，如果一致，换一种替换方法；如果不一致，输出

src/main/java/com/bogdatech/logic/PrivateKeyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/CaseSensitiveUtils.java
=> 修改词汇表的翻译逻辑

src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/PrintUtils.java
=> 修改打印日志的方法，修改统计的value判断

src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/PlaceholderUtils.java
=> 修改google翻译不了语言pt

src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/logic/PrivateKeyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/PlaceholderUtils.java
=> key中含css不翻译

src/main/java/com/bogdatech/controller/UserController.java, src/main/java/com/bogdatech/logic/PrivateKeyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/logic/UserService.java
1,修改筛选逻辑，key中有formId等数据的不翻译。
2，修改首次安装的邮件模板
=> 修改筛选逻辑，key中有formId等数据的不翻译。修改首次安装的邮件模板

src/main/java/com/bogdatech/logic/ShopifyService.java
=> 1,修改insertTargets出现null的问题

src/main/java/com/bogdatech/integration/ArkTranslateIntegration.java
=> 1,修改错误逻辑，并打印日志

src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 1,根据语言修改对应的模型翻译

src/main/java/com/bogdatech/entity/TranslateResourceDTO.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
1,根据语言修改对应的模型翻译
2,对于eamil的请求，只请求20条
=> 根据语言修改对应的模型翻译，对于eamil的请求，只请求20条

src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/integration/HunYuanIntegration.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/PlaceholderUtils.java
=> 修改提示词，对【】的变量做修改

src/main/java/com/bogdatech/integration/TranslateApiIntegration.java
=> 1, 令google自动判断源语言

pom.xml, src/main/java/com/bogdatech/config/ArkServiceConfig.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/controller/UserController.java, src/main/java/com/bogdatech/entity/TranslateResourceDTO.java, src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/integration/ArkTranslateIntegration.java, src/main/java/com/bogdatech/integration/HunYuanIntegration.java, src/main/java/com/bogdatech/integration/TranslateApiIntegration.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/logic/UserService.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java, src/main/java/com/bogdatech/utils/PlaceholderUtils.java
=> 修改翻译逻辑，改为其他大模型翻译

src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 1,fr使用豆包翻译

src/main/java/com/bogdatech/integration/ShopifyHttpIntegration.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/logic/UserPrivateService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
1,fr使用豆包翻译
2,添加修改主题数据打印日志
3，删除glossaryMap的打印日志
4,修改返回前端getUserData数据，多一个usedAmount
=> fr使用豆包翻译,删除glossaryMap的打印日志

src/main/java/com/bogdatech/logic/OrderService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/JudgeTranslateUtils.java
1,发送购买成功的邮件
2，hu语言改用qwen-max翻译
=> 发送购买成功的邮件,hu语言改用qwen-max翻译

src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 1,it也由qwen翻译

src/main/java/com/bogdatech/logic/OrderService.java
=> 1,修改邮件字符发送的方法

src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/integration/ArkTranslateIntegration.java, src/main/java/com/bogdatech/integration/HunYuanIntegration.java, src/main/java/com/bogdatech/logic/OrderService.java, src/main/java/com/bogdatech/utils/ApiCodeUtils.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
1,修改邮件字符发送的方法
2,修改提示词，语言代码改成具体语言
=> 修改邮件字符发送的方法和修改提示词，语言代码改成具体语言

src/main/java/com/bogdatech/controller/TranslationCounterController.java, src/main/java/com/bogdatech/utils/JudgeTranslateUtils.java
=> 1,修改添加额度的返回值

src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/entity/TranslateResourceDTO.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/utils/JudgeTranslateUtils.java
=> 1,product的逻辑调最后 2，theme不翻译

src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/integration/ArkTranslateIntegration.java, src/main/java/com/bogdatech/integration/HunYuanIntegration.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/CaseSensitiveUtils.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/PlaceholderUtils.java
=> 1,将提示词修改为极简，变量，词汇表的提示词

src/main/java/com/bogdatech/config/LanguageFlagConfig.java, src/main/java/com/bogdatech/utils/JudgeTranslateUtils.java
=> 1,修改主题方法 2，修改国旗翻译

src/main/java/com/bogdatech/Service/IUserSubscriptionsService.java, src/main/java/com/bogdatech/Service/impl/UserSubscriptionsServiceImpl.java, src/main/java/com/bogdatech/controller/UserController.java, src/main/java/com/bogdatech/entity/SubscriptionPlansDO.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/logic/UserService.java, src/main/java/com/bogdatech/task/RateTask.java
=> 1,修改计划的定时任务

src/main/java/com/bogdatech/Service/ITranslatesService.java, src/main/java/com/bogdatech/Service/impl/TranslatesServiceImpl.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/PlaceholderUtils.java
=> 1,状态6   2，提示词   3，元字段items数

src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/logic/PrivateKeyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/StringUtils.java
1,修改主题的翻译逻辑，如果是纯数字（包含小数，符数）不翻译
=> 1,修改主题的翻译逻辑，如果是纯数字（包含小数，符数）不翻译

src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/logic/PrivateKeyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/utils/StringUtils.java
=> 修改主题数据逻辑，纯数字，小数，负数不翻译

src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/JudgeTranslateUtils.java
1,修改主题的翻译逻辑，如果key中包含name翻译。对true或flase做判断然后翻译。json数据不回填
2，将google翻译去掉
3，德语用豆包翻译
=> 1,修改主题的翻译逻辑，如果key中包含name翻译。对true或flase做判断然后翻译。json数据不回填

src/main/java/com/bogdatech/utils/PlaceholderUtils.java
=> 1,修改正则表达式，再加上匹配【{{}}】 {}

src/main/java/com/bogdatech/logic/TranslateService.java
=> 1,在主题里面，html文本直接赛html集合里面

src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/model/controller/request/ResourceTypeRequest.java
=> 1，不要items功能

src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/integration/PrivateIntegration.java, src/main/java/com/bogdatech/logic/PrivateKeyService.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java
=> 1，修改NBSP的正则匹配

src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/integration/PrivateIntegration.java, src/main/java/com/bogdatech/logic/PrivateKeyService.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/model/controller/request/ResourceTypeRequest.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java, src/main/java/com/bogdatech/utils/PlaceholderUtils.java, src/main/java/com/bogdatech/utils/PrintUtils.java
进度条问题、希腊语变量翻译修改为豆包模型、元字段TRUE/FALSE不翻译，主题的的item前后一致
=> 进度条问题、希腊语变量翻译修改为豆包模型、元字段TRUE/FALSE不翻译，主题的的item前后一致

src/main/java/com/bogdatech/Service/impl/TranslatesServiceImpl.java, src/main/java/com/bogdatech/entity/TranslatesDO.java
=> 1，修改单条最近的翻译项数据

src/main/java/com/bogdatech/Service/ITranslatesService.java, src/main/java/com/bogdatech/Service/impl/TranslatesServiceImpl.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/logic/PrivateKeyService.java, src/main/java/com/bogdatech/logic/TaskService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/task/TranslateTask.java
=> 重启后恢复状态为2的翻译任务

src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/task/TranslateTask.java, src/main/java/com/bogdatech/utils/JudgeTranslateUtils.java
=> 重新实现服务器重启后，将翻译状态为2的任务重新进行翻译

src/main/java/com/bogdatech/controller/WidgetConfigurationsController.java
=> 1,修改switch查询逻辑

src/main/java/com/bogdatech/controller/WidgetConfigurationsController.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
1,变量由qwenmax翻译
2.元字段的True和false无论大小写都不翻译
=> 变量由qwenmax翻译和元字段的True和false无论大小写都不翻译

src/main/java/com/bogdatech/Service/IUserIPSwitchService.java, src/main/java/com/bogdatech/Service/impl/UserIPSwitchServiceImpl.java
=> 1,修改getSwitchId的返回值数据

src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 1,只允许ar变量用qwen翻译

src/main/java/com/bogdatech/Service/impl/TranslatesServiceImpl.java, src/main/java/com/bogdatech/mapper/TranslatesMapper.java
=> 1,修改获取翻译项数据的方法

src/main/java/com/bogdatech/constants/MailChimpConstants.java, src/main/java/com/bogdatech/controller/CharsOrdersController.java, src/main/java/com/bogdatech/logic/OrderService.java, src/main/java/com/bogdatech/task/RateTask.java
=> 订阅成功邮件发送的方法

src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/task/RateTask.java
=> 1，元字段html翻译

src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/entity/VO/SubscriptionVO.java
=> 1,修改订阅计划的方法

src/main/java/com/bogdatech/entity/TranslateResourceDTO.java
=> 1,翻译逻辑先去掉object

src/main/java/com/bogdatech/entity/TranslateResourceDTO.java, src/main/java/com/bogdatech/logic/TranslateService.java
=> 1,handel可以翻译  2，object也可以翻译

src/main/java/com/bogdatech/logic/PrivateKeyService.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/JudgeTranslateUtils.java
=> 1,handle数据翻译，token计数也计数

src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/logic/PrivateKeyService.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TaskService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/ModelUtils.java
=> 1,URL的只有handle翻译，修改翻译顺序

src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/logic/TranslateService.java
=> 1,修改handle翻译 2，顺序的判断

src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/entity/TranslateResourceDTO.java
=> 1,打印日志用户的传入模块数据

src/main/java/com/bogdatech/entity/TranslateResourceDTO.java
=> 1,object翻译

src/main/java/com/bogdatech/logic/TranslateService.java
=> 1,测试为什么翻译停止

src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/entity/TranslateResourceDTO.java, src/main/java/com/bogdatech/integration/ArkTranslateIntegration.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TaskService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/utils/ModelUtils.java
=> 1,定位翻译失败的原因

src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/logic/TranslateService.java
=> 1，获取订阅计划方法修改

src/main/java/com/bogdatech/utils/JudgeTranslateUtils.java
1, theme主题既包含.json，又包含code 的key不翻译
=> 1, theme主题既包含.json，又包含code, variant_ 的key不翻译

src/main/java/com/bogdatech/utils/JudgeTranslateUtils.java
=> 1, 将checkout添加到翻译白名单里面

src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/JudgeTranslateUtils.java
=> 1, 单条文本翻译 2,rtl 不翻译

src/main/java/com/bogdatech/config/RabbitMQConfig.java, src/main/java/com/bogdatech/constants/RabbitMQConstants.java, src/main/java/com/bogdatech/utils/PlaceholderUtils.java, src/main/resources/application.properties
1,将Rabbit的服务密码都部署到Azure里面调用
2,修改普通翻译的提示词
=> 1,将Rabbit的服务密码都部署到Azure里面调用 2,修改普通翻译的提示词

src/main/java/com/bogdatech/logic/TaskService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/model/service/TranslateTaskConsumerService.java
=> 1,修改邮件发送逻辑 2,修改状态逻辑

src/main/java/com/bogdatech/logic/ShopifyService.java
=> 1,修改shopify本地单条数据逻辑

src/main/java/com/bogdatech/utils/JudgeTranslateUtils.java
=> 1,修改theme，key值判断

src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/UserTypeTokenService.java
=> 1,初始化的过程中，计算一个不存在语言的值

src/main/java/com/bogdatech/config/RabbitMQConfig.java, src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 1,修改单条翻译的token方法

src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 1,做token的打印日志

src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/integration/ArkTranslateIntegration.java, src/main/java/com/bogdatech/integration/HunYuanIntegration.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java
=> 1,打印每条文本的token数

src/main/java/com/bogdatech/constants/TranslateConstants.java, src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/integration/ArkTranslateIntegration.java, src/main/java/com/bogdatech/integration/HunYuanIntegration.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 1,删除日志的打印2，修改单条翻译信息 3，修改存储判断

src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/integration/PrivateIntegration.java, src/main/java/com/bogdatech/logic/PrivateKeyService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 1,修改翻译逻辑的empty判断

src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java
1，自动翻译，token消耗为0，不发短信 在singleTextTranslate分支
2，METAOBJECT里面json数据不翻译
=> 1，自动翻译，token消耗为0，不发短信 在singleTextTranslate分支 2，METAOBJECT里面json数据不翻译

src/main/java/com/bogdatech/logic/TranslateService.java
=> 1,用户消耗token为0，不发邮件

src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java
=> 1,修改保存判断逻辑

src/main/java/com/bogdatech/config/RabbitMQConfig.java, src/main/java/com/bogdatech/constants/TranslateConstants.java, src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/integration/ArkTranslateIntegration.java, src/main/java/com/bogdatech/integration/HunYuanIntegration.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java, src/main/java/com/bogdatech/utils/PlaceholderUtils.java, src/main/java/com/bogdatech/utils/SwitchModelUtils.java
=> 1,handle翻译

src/main/java/com/bogdatech/constants/TranslateConstants.java, src/main/java/com/bogdatech/controller/EmailController.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/SwitchModelUtils.java
=> 1,修改单条handle翻译

src/main/java/com/bogdatech/constants/TranslateConstants.java, src/main/java/com/bogdatech/logic/TranslateService.java
=> 1,修改单条handle翻译,将URL改为URI

src/main/java/com/bogdatech/controller/TranslateController.java
=> 1, 对前端的参数做判断

src/main/java/com/bogdatech/logic/TranslateService.java
=> 1, html 加上continue

src/main/java/com/bogdatech/logic/TranslateService.java
1,qnxrrk-2n.myshopify.com  gemxco.myshopify.com
再加个ciwi的商店里PRODUCT_OPTION里面不翻译
=> 1,qnxrrk-2n.myshopify.com  gemxco.myshopify.com   再加个ciwi的商店里PRODUCT_OPTION里面不翻译

src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/logic/TranslateService.java
1,qnxrrk-2n.myshopify.com   gemxco.myshopify.com   再加个ciwi的商店里PRODUCT_OPTION里面不翻译
=> 1,qnxrrk-2n.myshopify.com   gemxco.myshopify.com   再加个ciwi的商店里PRODUCT_OPTION里面不翻译

src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/JudgeTranslateUtils.java
1,PRODUCT_OPTION和PRODUCT_OPTION_VALUE，三个用户不翻译
2，s'watch不翻译
=> 1,PRODUCT_OPTION和PRODUCT_OPTION_VALUE，三个用户不翻译 2，s'watch不翻译

src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/JudgeTranslateUtils.java
[1,对翻译的key添加option:](https://github.com/whoeven99/SpringBackend/commit/3d7b4c8a2c22e2591e18fc36f7e08e07f6e5c2f5)
=> 1,对翻译的key添加option:

src/main/java/com/bogdatech/logic/TaskService.java
=> 1,修改一下定时加额度的办法

src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 1,el 由 qwen-max翻译

src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/logic/TaskService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/StringUtils.java
=> 1,语言大小写，处理

src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 1,删掉语言大小写判断

src/main/java/com/bogdatech/utils/JsoupUtils.java
[1,将混元改为qwen](https://github.com/whoeven99/SpringBackend/pull/577)
=>  1,将混元改为qwen

src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/integration/HunYuanIntegration.java, src/main/java/com/bogdatech/integration/ShopifyHttpIntegration.java, src/main/java/com/bogdatech/integration/TestingEnvironmentIntegration.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/StringUtils.java
1,切换混元翻译 做id打印
2,metafiled html要做格式处理 
3,部分请求做指数退避,
=> 1,切换混元翻译 做id打印 2,metafiled html要做格式处理  3,部分请求做指数退避,

src/main/java/com/bogdatech/logic/TranslateService.java
=> 1,单条翻译HTML或格式处理

src/main/java/com/bogdatech/integration/HunYuanIntegration.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TaskService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/JsonUtils.java
1,handle 暂时改为不翻译
2，订阅计划，卸载的用户不请求
3, 修改插入失败的error信息
=> 1,handle 暂时改为不翻译 2，订阅计划，卸载的用户不请求 3, 修改插入失败的error信息

src/main/java/com/bogdatech/Service/ITranslationCounterService.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/controller/UserTypeTokenController.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/model/service/TranslateTaskConsumerService.java
1，handle 打印日志
2，定时翻译用user表里面的token
=> 1，handle 打印日志 2，定时翻译用user表里面的token

src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java
=> 1，token 重新计数 2，handle翻译

src/main/java/com/bogdatech/integration/ShopifyHttpIntegration.java, src/main/java/com/bogdatech/logic/ShopifyService.java
=> 1，修改失败打印日志，使打印更多错误信息

src/main/java/com/bogdatech/controller/APGDescriptionGenerationController.java, src/main/java/com/bogdatech/entity/VO/GenerateVO.java
1，添加GenerateVO，用于传输描述生成后的描述，pageType，contentType
=> 1，添加GenerateVO，用于传输描述生成后的描述，pageType，contentType

src/main/java/com/bogdatech/controller/APGDescriptionGenerationController.java, src/main/java/com/bogdatech/controller/UserController.java, src/main/java/com/bogdatech/entity/VO/GenerateVO.java
=> 1，修改打印参数，和传值问题

src/main/java/com/bogdatech/Service/IAPGTemplateService.java, src/main/java/com/bogdatech/Service/impl/APGTemplateServiceImpl.java, src/main/java/com/bogdatech/controller/APGTemplateController.java, src/main/java/com/bogdatech/entity/DO/APGTemplateDO.java, src/main/java/com/bogdatech/logic/GenerateDescriptionService.java
…archar(200),template_type bit,template_seo bit,shop_name    nvarchar(255)（用于存放模板相关数据（默认数据和用户自定义数据））。修改查询方法，将相关数据一次性传给前端。
2,修改查询方法，根据shopName将获取到的相关数据一次性传给前端
=> 1，修改APG_Template表格

src/main/java/com/bogdatech/model/service/StoringDataConsumerService.java
1，创建用户存储队列，交换机，路由key。
2，创建用户存储死信队列，交换机，路由key
3，翻译后的数据改用mq存储到shopify
4,userStoreData设置3 个并发线程，每人只拿一条消息处理，刚好同时处理 3 条。
=> userStoreData设置3 个并发线程，每人只拿一条消息处理，刚好同时处理 3 条。

src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/integration/ArkTranslateIntegration.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
1,翻译成en用qwen-max翻译
2,当混元报错时，再用qwen翻译
=> 1,翻译成en用qwen-max翻译

src/main/java/com/bogdatech/Service/IUserTrialsService.java, src/main/java/com/bogdatech/Service/impl/UserTrialsServiceImpl.java, src/main/java/com/bogdatech/entity/DO/UserTrialsDO.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/mapper/UserTrialsMapper.java
=> 1,设计并实现用户免费试用表

src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/PlaceholderUtils.java
=> 1,翻译前打印相关提示词

src/main/java/com/bogdatech/constants/MailChimpConstants.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/integration/ArkTranslateIntegration.java, src/main/java/com/bogdatech/integration/EmailIntegration.java, src/main/java/com/bogdatech/integration/HunYuanIntegration.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/PlaceholderUtils.java
=> 1,修改相关提示词 2,邮件抄送

src/main/java/com/bogdatech/Service/impl/UserTrialsServiceImpl.java, src/main/java/com/bogdatech/logic/TranslateService.java
=> 1,5天改为6小时后面改回来

src/main/java/com/bogdatech/controller/GlossaryController.java, src/main/java/com/bogdatech/logic/TranslateService.java
=> 1，将词汇表限制注释掉

src/main/java/com/bogdatech/Service/impl/UserTrialsServiceImpl.java, src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/integration/ArkTranslateIntegration.java, src/main/java/com/bogdatech/integration/HunYuanIntegration.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TaskService.java, src/main/java/com/bogdatech/logic/UserTrialsService.java, src/main/java/com/bogdatech/utils/PrintUtils.java
1,做token 统计打印日志
2，做对计划为active的判断
3，修改过期时间
=> 1,做token 统计打印日志

src/main/java/com/bogdatech/logic/GenerateDescriptionService.java, src/main/java/com/bogdatech/utils/GenerateDescriptionUtils.java
2，修改新应用的id获取方法，根据pageType获取query
3,根据ContentType选择提示词
4,根据type解析data
=> 1,定位元字段翻译问题（都是在元字段停止，并发修改的问题）

src/main/java/com/bogdatech/logic/GenerateDescriptionService.java, src/main/java/com/bogdatech/logic/TranslateService.java
1,定位元字段翻译问题（都是在元字段停止，并发修改的问题）
2，修改新应用的id获取方法，根据pageType获取query
3,根据ContentType选择提示词
4,根据type解析data
=> 1,定位元字段翻译问题（都是在元字段停止，并发修改的问题） 2，修改新应用的id获取方法，根据pageType获取query 3,根据ContentType选择提示词 4,根据type解析data

src/main/java/com/bogdatech/Service/IUserIpService.java, src/main/java/com/bogdatech/Service/impl/UserIpServiceImpl.java, src/main/java/com/bogdatech/controller/UserIpController.java, src/main/java/com/bogdatech/entity/DO/UserIpDO.java, src/main/java/com/bogdatech/logic/UserIpService.java, src/main/java/com/bogdatech/mapper/UserIpMapper.java, src/main/java/com/bogdatech/utils/JudgeTranslateUtils.java, src/main/java/com/bogdatech/utils/PlaceholderUtils.java
1,电话号码判断
2，提示词空格问题
3，UserIp表方法
=> 1,电话号码判断2，提示词空格问题 3，UserIp表方法

src/main/java/com/bogdatech/logic/GenerateDescriptionService.java, src/main/java/com/bogdatech/utils/GenerateDescriptionUtils.java
=> 1,新app seo提示词

src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/integration/ArkTranslateIntegration.java, src/main/java/com/bogdatech/integration/HunYuanIntegration.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
1,修改打印日志，加空格
2，source为 ro 改qwen翻译
=> 1,修改打印日志，加空格

src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/integration/ArkTranslateIntegration.java, src/main/java/com/bogdatech/integration/HunYuanIntegration.java, src/main/java/com/bogdatech/logic/AILanguagePackService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 1,修改打印日志，在消耗打印加用户

src/main/java/com/bogdatech/config/CurrencyConfig.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/JudgeTranslateUtils.java, src/main/java/com/bogdatech/utils/MapUtils.java
1,货币问题
2，theme中HTML直接翻译
3, 目标为nl的放到qwen翻译
=> 1,货币问题 2，theme中HTML直接翻译 3, 目标为nl的放到qwen翻译

src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java
=> 1,放开单条翻译的限制

src/main/java/com/bogdatech/utils/JudgeTranslateUtils.java
=> 1,修改json的判断，修改打印日志

src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/logic/RabbitMqTranslateService.java, src/main/java/com/bogdatech/model/service/StoringDataPublisherService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 1,修改一些打印日志

src/main/java/com/bogdatech/constants/TranslateConstants.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/entity/DO/TranslateResourceDTO.java, src/main/java/com/bogdatech/logic/OrderService.java, src/main/java/com/bogdatech/logic/TencentEmailService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/model/service/RabbitMqTranslateConsumerService.java, src/main/java/com/bogdatech/task/RabbitMqTask.java
1,修改锁的设置2，修改product和元字段的请求数量 为60 3，修改购买邮件的总共字符数为剩余字符数
=> 1,修改锁的设置2，修改product和元字段的请求数量 为60 3，修改购买邮件的总共字符数为剩余字符数

src/main/java/com/bogdatech/logic/OrderService.java
1,修改购买邮件发送，当购买的token大于（最大额度-已使用额度），展示购买额度。反之。展示最大额度-已使用额度
=> 1,修改购买邮件发送，当购买的token大于（最大额度-已使用额度），展示购买额度。反之。展示最大额度-已使用额度

src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/logic/TranslateService.java
2，修改翻译逻辑线程池配置改为4，8
3,修改服务器重启后的恢复，将测试表的用户的翻译数据改为0
=> 1,修改主题判断逻辑，舍去白名单规则，改为判断开头是否是general.或section.，再走key值判断

src/main/java/com/bogdatech/logic/PrivateKeyService.java, src/main/java/com/bogdatech/logic/ShopifyService.java
=> 1,把DB翻译逻辑也修改一下

src/main/java/com/bogdatech/logic/RabbitMqTranslateService.java
=> 1,修改handle翻译

src/main/java/com/bogdatech/logic/RabbitMqTranslateService.java, src/main/java/com/bogdatech/logic/TaskService.java, src/main/java/com/bogdatech/logic/TencentEmailService.java, src/main/java/com/bogdatech/model/service/RabbitMqTranslateConsumerService.java, src/main/java/com/bogdatech/utils/JudgeTranslateUtils.java
=> 1,http://类数据只开头才名中

src/main/java/com/bogdatech/Service/impl/TranslateTasksServiceImpl.java, src/main/java/com/bogdatech/model/service/RabbitMqTranslateConsumerService.java
=> 1,修改字符限制的打印问题 2，字符 限制后，将2改为3

src/main/java/com/bogdatech/Service/ITranslateTasksService.java, src/main/java/com/bogdatech/Service/impl/TranslateTasksServiceImpl.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/logic/RabbitMqTranslateService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/model/service/RabbitMqTranslateConsumerService.java
1，修改mq翻译方法，返回值放到状态改为2后给前端
2，修改卸载方法
=> 1，修改mq翻译方法，返回值放到状态改为2后给前端 2，修改卸载方法

src/main/java/com/bogdatech/model/service/RabbitMqTranslateConsumerService.java
=> 1，修改额度不够的task状态

src/main/java/com/bogdatech/logic/RabbitMqTranslateService.java, src/main/java/com/bogdatech/task/RabbitMqTask.java, src/main/java/com/bogdatech/task/RateTask.java
=> 1，测试，修改test的自动翻译

src/main/java/com/bogdatech/Service/impl/TranslateTasksServiceImpl.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/logic/PrivateKeyService.java, src/main/java/com/bogdatech/logic/RabbitMqTranslateService.java, src/main/java/com/bogdatech/logic/TencentEmailService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/model/service/RabbitMqTranslateConsumerService.java, src/main/java/com/bogdatech/task/RabbitMqTask.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/utils/ListUtils.java, src/main/java/com/bogdatech/utils/ResourceTypeUtils.java
=> 1，修改部分模块邮件发送

src/main/java/com/bogdatech/config/RabbitMQConfig.java, src/main/java/com/bogdatech/model/service/RabbitMqTranslateConsumerService.java, src/main/java/com/bogdatech/utils/ResourceTypeUtils.java
=> 1，修改用户DB翻译部分邮件发送的问题

src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/logic/RabbitMqTranslateService.java, src/main/java/com/bogdatech/model/service/RabbitMqTranslateConsumerService.java, src/main/java/com/bogdatech/utils/ListUtils.java
1，修改用户DB翻译部分邮件发送的问题
2, 实现状态3，15分钟后发送邮件
=> 1，修改用户DB翻译部分邮件发送的问题 2, 实现状态3，15分钟后发送邮件

src/main/java/com/bogdatech/logic/RabbitMqTranslateService.java, src/main/java/com/bogdatech/model/service/RabbitMqTranslateConsumerService.java
1，修改用户DB翻译部分邮件发送的问题
2, 实现状态3，10分钟后发送邮件,仅限翻译完成
=> 1，修改用户DB翻译部分邮件发送的问题 2, 实现状态3，10分钟后发送邮件,仅限翻译完成

src/main/java/com/bogdatech/integration/DeepLIntegration.java, src/main/java/com/bogdatech/logic/RabbitMqTranslateService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 1，对handle翻译进行判断，20以内用mt；以上用大模型

src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 1，在handle里面，变量用变量提示词翻译

src/main/java/com/bogdatech/utils/JudgeTranslateUtils.java
1，覆盖翻译
2， 订阅邮件发送
3，修改卸载方法，重新实现对IP的卸载处理，关掉ip开关
4,类hash数据不翻译
=> 1，覆盖翻译 2， 订阅邮件发送 3，修改卸载方法，重新实现对IP的卸载处理，关掉ip开关 4,类hash数据不翻译

src/main/java/com/bogdatech/utils/ApiCodeUtils.java
=> 1，sr改为拉丁语版本

src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java
=> 1，删除html中对空格的处理

src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/entity/VO/RabbitMqTranslateVO.java, src/main/java/com/bogdatech/logic/RabbitMqTranslateService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/model/controller/request/ClickTranslateRequest.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java, src/main/java/com/bogdatech/utils/PlaceholderUtils.java
=> 1，自定义提示词 2，将空格清除还原

src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java
1，对HTML的文本进行处理，在翻译前记录是否有空格，翻译后在恢复回去。
=> 1，对HTML的文本进行处理，在翻译前记录是否有空格，翻译后在恢复回去。

src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java
=> 1，对于emoji翻译修改问题

src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java
=> 1，修改一下匹配规则

src/main/java/com/bogdatech/controller/UserPicturesController.java
=> 1，对图片的格式进行限制

src/main/resources/application.properties
=> 1，设置图片最大限制 20mb

src/main/resources/application.properties
=> 1，将openai版本 改为4.1

src/main/java/com/bogdatech/constants/TranslateConstants.java, src/main/java/com/bogdatech/controller/APGDescriptionGenerationController.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/entity/DTO/FullAttributeSnapshotDTO.java, src/main/java/com/bogdatech/integration/ChatGptIntegration.java, src/main/java/com/bogdatech/integration/DeepLIntegration.java, src/main/java/com/bogdatech/logic/RabbitMqTranslateService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java, src/main/resources/application.properties
1，修改product和article的html翻译逻辑，改为替换属性后，全量翻译，再回填
2，修改openai和deepl的倍率
=> 1，修改product和article的html翻译逻辑，改为替换属性后，全量翻译，再回填 2，修改openai和deepl的倍率

src/main/java/com/bogdatech/constants/TranslateConstants.java, src/main/java/com/bogdatech/controller/APGDescriptionGenerationController.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/entity/DTO/FullAttributeSnapshotDTO.java, src/main/java/com/bogdatech/integration/ChatGptIntegration.java, src/main/java/com/bogdatech/integration/DeepLIntegration.java, src/main/java/com/bogdatech/logic/RabbitMqTranslateService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java, src/main/resources/application.properties
=> 1，修改单条翻译html的逻辑

src/main/java/com/bogdatech/Service/IAPGOfficialTemplateService.java, src/main/java/com/bogdatech/Service/IAPGUserProductService.java, src/main/java/com/bogdatech/Service/IAPGUserTemplateMappingService.java, src/main/java/com/bogdatech/Service/IAPGUsersService.java, src/main/java/com/bogdatech/Service/impl/APGOfficialTemplateServiceImpl.java, src/main/java/com/bogdatech/Service/impl/APGTemplateServiceImpl.java, src/main/java/com/bogdatech/Service/impl/APGUserCounterServiceImpl.java, src/main/java/com/bogdatech/Service/impl/APGUserProductServiceImpl.java, src/main/java/com/bogdatech/Service/impl/APGUserTemplateMappingServiceImpl.java, src/main/java/com/bogdatech/Service/impl/APGUsersServiceImpl.java, src/main/java/com/bogdatech/controller/APGTemplateController.java, src/main/java/com/bogdatech/controller/APGUserProductController.java, src/main/java/com/bogdatech/controller/APGUsersController.java, src/main/java/com/bogdatech/entity/DO/APGOfficialTemplateDO.java, src/main/java/com/bogdatech/entity/DO/APGUserCounterDO.java, src/main/java/com/bogdatech/entity/DO/APGUserProductDO.java, src/main/java/com/bogdatech/entity/DO/APGUserTemplateMappingDO.java, src/main/java/com/bogdatech/entity/DTO/TemplateDTO.java, src/main/java/com/bogdatech/logic/APGTemplateService.java, src/main/java/com/bogdatech/logic/APGUserProductService.java, src/main/java/com/bogdatech/logic/APGUserService.java, src/main/java/com/bogdatech/logic/GenerateDescriptionService.java, src/main/java/com/bogdatech/mapper/APGOfficialTemplateMapper.java, src/main/java/com/bogdatech/mapper/APGTemplateMapper.java, src/main/java/com/bogdatech/mapper/APGUserCounterMapper.java, src/main/java/com/bogdatech/mapper/APGUserProductMapper.java, src/main/java/com/bogdatech/mapper/APGUserTemplateMappingMapper.java
1，修改原先的数据库表格，及相关方法
2，设计并实现用户产品表，实现读，写，删方法
3，重新实现模板表，实现模板映射表。实现读方法。
4，修改用户初始化的方法，默认初始化前4条模板
=> 1，修改原先的数据库表格，及相关方法 2，设计并实现用户产品表，实现读，写，删方法 3，重新实现模板表，实现模板映射表。实现读方法。 4，修改用户初始化的方法，默认初始化前4条模板

src/main/java/com/bogdatech/Service/IAPGUserProductService.java, src/main/java/com/bogdatech/Service/impl/APGUserProductServiceImpl.java, src/main/java/com/bogdatech/controller/APGTemplateController.java, src/main/java/com/bogdatech/entity/DO/APGUserProductDO.java, src/main/java/com/bogdatech/logic/APGTemplateService.java, src/main/java/com/bogdatech/logic/GenerateDescriptionService.java, src/main/java/com/bogdatech/mapper/APGUserProductMapper.java
1，修改获取所有模板数据的方法，添加templateModel,templateSubtype, templateClass, templateType参数，在获取时做判断获取
2, 修改APG_User_Product表格，添加一个字段generateContent用于存储生成的描述
=> 1，修改获取所有模板数据的方法，添加templateModel,templateSubtype, templateClass, templateType参数，在获取时做判断获取 2, 修改APG_User_Product表格，添加一个字段generateContent用于存储生成的描述

src/main/java/com/bogdatech/controller/APGTemplateController.java, src/main/java/com/bogdatech/controller/APGUserGeneratedTaskController.java, src/main/java/com/bogdatech/entity/DTO/TemplateDTO.java, src/main/java/com/bogdatech/logic/APGTemplateService.java, src/main/java/com/bogdatech/requestBody/ShopifyRequestBody.java
=> 1,创建用户模板，添加其映射关系

src/main/java/com/bogdatech/Service/IAPGEmailService.java, src/main/java/com/bogdatech/Service/IAPGUserGeneratedSubtaskService.java, src/main/java/com/bogdatech/Service/impl/APGEmailServiceImpl.java, src/main/java/com/bogdatech/Service/impl/APGUserGeneratedSubtaskServiceImpl.java, src/main/java/com/bogdatech/constants/MailChimpConstants.java, src/main/java/com/bogdatech/controller/APGDescriptionGenerationController.java, src/main/java/com/bogdatech/controller/APGUserGeneratedTaskController.java, src/main/java/com/bogdatech/controller/EmailController.java, src/main/java/com/bogdatech/entity/DO/APGEmailDO.java, src/main/java/com/bogdatech/logic/APGUserGeneratedTaskService.java, src/main/java/com/bogdatech/logic/APGUserService.java, src/main/java/com/bogdatech/logic/TencentEmailService.java, src/main/java/com/bogdatech/mapper/APGEmailMapper.java, src/main/java/com/bogdatech/mapper/APGUserGeneratedSubtaskMapper.java, src/main/java/com/bogdatech/task/GenerateDbTask.java
1,设计和实现用户邮件表，实现用户初始化邮件
2，发送邮件方法进行处理,对未处理的数据改为0，3，4
=> 1,设计和实现用户邮件表，实现用户初始化邮件 2，发送邮件方法进行处理,对未处理的数据改为0，3，4

src/main/java/com/bogdatech/Service/IAPGUserGeneratedTaskService.java, src/main/java/com/bogdatech/Service/impl/APGUserGeneratedTaskServiceImpl.java, src/main/java/com/bogdatech/controller/APGUserGeneratedTaskController.java, src/main/java/com/bogdatech/logic/APGUserGeneratedTaskService.java, src/main/java/com/bogdatech/mapper/APGUserGeneratedTaskMapper.java
=> 1,添加一个修改状态为2的方法

src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/logic/GenerateDescriptionService.java
=> 1,当产品没有图片时要换模型调用

src/main/java/com/bogdatech/Service/IAPGUserProductService.java, src/main/java/com/bogdatech/Service/impl/APGUserProductServiceImpl.java, src/main/java/com/bogdatech/entity/DO/APGUserProductDO.java, src/main/java/com/bogdatech/entity/VO/GenerateDescriptionVO.java, src/main/java/com/bogdatech/logic/GenerateDescriptionService.java, src/main/java/com/bogdatech/logic/TencentEmailService.java, src/main/java/com/bogdatech/mapper/APGUserProductMapper.java, src/main/java/com/bogdatech/utils/TypeConversionUtils.java
1,修改APG产品表格，添加一个字段productType用于存放用户选择模型
2，修改相关方法
=> 1,修改APG产品表格，添加一个字段productType用于存放用户选择模型 2，修改相关方法

src/main/java/com/bogdatech/controller/APGUsersController.java, src/main/java/com/bogdatech/logic/APGUserGeneratedTaskService.java, src/main/java/com/bogdatech/logic/APGUserService.java, src/main/java/com/bogdatech/task/GenerateDbTask.java
1, 修改用户批量生成暂停方法，点击后将任务状态改为0，子任务改成5
=> 1, 修改用户批量生成暂停方法，点击后将任务状态改为0，子任务改成5

src/main/java/com/bogdatech/Service/IAPGUserGeneratedSubtaskService.java, src/main/java/com/bogdatech/Service/impl/APGUserGeneratedSubtaskServiceImpl.java, src/main/java/com/bogdatech/logic/APGUserGeneratedTaskService.java, src/main/java/com/bogdatech/logic/GenerateDescriptionService.java, src/main/java/com/bogdatech/mapper/APGUserGeneratedSubtaskMapper.java, src/main/java/com/bogdatech/utils/PlaceholderUtils.java
=> 1, 修改获取html的数据descriptionHtml

src/main/java/com/bogdatech/mapper/APGUserGeneratedSubtaskMapper.java
1, 在下一次的翻译时，将问题数据3，4都改为5(修改修改语句)
=> 1, 在下一次的翻译时，将问题数据3，4都改为5(修改修改语句)

src/main/java/com/bogdatech/controller/APGDescriptionGenerationController.java, src/main/java/com/bogdatech/controller/APGUserGeneratedTaskController.java, src/main/java/com/bogdatech/utils/TypeConversionUtils.java
=> 1, 将类型转换方法的参数修改

src/main/java/com/bogdatech/Service/IAPGCharsOrderService.java, src/main/java/com/bogdatech/Service/IAPGOfficialTemplateService.java, src/main/java/com/bogdatech/Service/impl/APGCharsOrderServiceImpl.java, src/main/java/com/bogdatech/Service/impl/APGOfficialTemplateServiceImpl.java, src/main/java/com/bogdatech/controller/APGCharsOrderController.java, src/main/java/com/bogdatech/controller/APGTemplateController.java, src/main/java/com/bogdatech/entity/DO/APGCharsOrderDO.java, src/main/java/com/bogdatech/entity/DO/APGOfficialTemplateDO.java, src/main/java/com/bogdatech/logic/APGCharsOrderService.java, src/main/java/com/bogdatech/logic/APGTemplateService.java, src/main/java/com/bogdatech/mapper/APGCharsOrderMapper.java, src/main/java/com/bogdatech/mapper/APGOfficialTemplateMapper.java
1, 设计并实现生成订单表，实现写方法
2，添加example_date字段，添加preview方法，获取数据库对应数据
3，在创建自定义用户模板后，添加对应映射方法
=> 1, 设计并实现生成订单表，实现写方法 2，添加example_date字段，添加preview方法，获取数据库对应数据 3，在创建自定义用户模板后，添加对应映射方法

src/main/java/com/bogdatech/controller/APGUserGeneratedTaskController.java
=> 1, 打印一下暂停的报错

src/main/java/com/bogdatech/controller/APGUserGeneratedTaskController.java, src/main/java/com/bogdatech/model/service/StoringDataConsumerService.java
=> 1, 修改存储线程的大小

src/main/java/com/bogdatech/config/RabbitMQConfig.java, src/main/java/com/bogdatech/constants/RabbitMQConstants.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/model/service/StoringDataConsumerService.java, src/main/java/com/bogdatech/model/service/StoringDataPublisherService.java
1, 修改存储方法，然后该用户被锁了之后，放到延迟队列，在发送
=> 1, 修改存储方法，然后该用户被锁了之后，放到延迟队列，在发送

src/main/java/com/bogdatech/logic/ShopifyService.java
=> 1, 将异步写，改为同步写

src/main/java/com/bogdatech/Service/IUserTranslationDataService.java, src/main/java/com/bogdatech/Service/impl/UserTranslationDataServiceImpl.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/entity/DO/UserTranslationDataDO.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/UserTranslationDataService.java, src/main/java/com/bogdatech/mapper/UserTranslationDataMapper.java, src/main/java/com/bogdatech/task/SaveShopifyDataTask.java
1，设计并实现UserTranslationData表，实现相关CRUD方法
2，修改存储shopify的逻辑，在翻译完先存到数据库。每1s后从数据库获取8个不同用户的翻译数据，将状态改为2，遍历存储到shopify.存完后删除该数据
=> 1，设计并实现UserTranslationData表，实现相关CRUD方法 2，修改存储shopify的逻辑，在翻译完先存到数据库。每1s后从数据库获取8个不同用户的翻译数据，将状态改为2，遍历存储到shopify.存完后删除该数据

src/main/java/com/bogdatech/controller/APGUserCounterController.java, src/main/java/com/bogdatech/entity/VO/APGTokenVO.java
1, 实现APGTokenVO类型数据，用于返回给前端额度展示
=> 1, 实现APGTokenVO类型数据，用于返回给前端额度展示

src/main/java/com/bogdatech/logic/APGCharsOrderService.java
=> 1, 存的时候，添加下userId

src/main/java/com/bogdatech/logic/UserTranslationDataService.java, src/main/java/com/bogdatech/task/SaveShopifyDataTask.java
=> 1, 异步存储用户翻译数据

src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/logic/TaskService.java
=> 1, 当服务器重启时，初始化用户停止标识

src/main/java/com/bogdatech/task/GenerateDbTask.java
=> 1, 测试周五实现的通过数据强化创建的内容可信度的方法

src/main/java/com/bogdatech/constants/MailChimpConstants.java, src/main/java/com/bogdatech/controller/APGUserCounterController.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/integration/EmailIntegration.java, src/main/java/com/bogdatech/logic/APGCharsOrderService.java, src/main/java/com/bogdatech/logic/APGUserGeneratedTaskService.java, src/main/java/com/bogdatech/logic/TencentEmailService.java, src/main/java/com/bogdatech/task/GenerateDbTask.java, src/main/java/com/bogdatech/task/TranslateTask.java
1, 新应用购买成功后，发送购买成功的邮件 
2，应用中，翻译任务中断，发送邮件
=> 1, 新应用购买成功后，发送购买成功的邮件 2，应用中，翻译任务中断，发送邮件

src/main/java/com/bogdatech/task/GenerateDbTask.java
1, 新应用购买成功后，发送购买成功的邮件 
2，应用中，翻译任务中断，发送邮件,修改获取的参数
=> 1, 新应用购买成功后，发送购买成功的邮件 2，应用中，翻译任务中断，发送邮件,修改获取的参数

src/main/java/com/bogdatech/Service/impl/TranslationUsageServiceImpl.java, src/main/java/com/bogdatech/controller/APGDescriptionGenerationController.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/logic/GenerateDescriptionService.java, src/main/java/com/bogdatech/logic/TestService.java, src/main/java/com/bogdatech/model/service/RabbitMqTranslateConsumerService.java, src/main/java/com/bogdatech/task/AutoTranslateTask.java, src/main/java/com/bogdatech/utils/PlaceholderUtils.java
=> 1, 新app的提示词

src/main/java/com/bogdatech/controller/APGUserGeneratedTaskController.java, src/main/java/com/bogdatech/entity/DO/APGUserGeneratedTaskDO.java, src/main/java/com/bogdatech/entity/VO/GenerateProgressBarVO.java, src/main/java/com/bogdatech/logic/APGUserGeneratedTaskService.java, src/main/java/com/bogdatech/logic/GenerateDescriptionService.java, src/main/java/com/bogdatech/logic/TencentEmailService.java, src/main/java/com/bogdatech/model/service/RabbitMqTranslateConsumerService.java, src/main/java/com/bogdatech/task/GenerateDbTask.java, src/main/java/com/bogdatech/utils/PlaceholderUtils.java
1, 修改新app的提示词 
2，添加进度条状态和最新一次任务时间的参数
=> 1, 修改新app的提示词 2，添加进度条状态和最新一次任务时间的参数

src/main/java/com/bogdatech/controller/APGDescriptionGenerationController.java, src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/logic/GenerateDescriptionService.java, src/main/java/com/bogdatech/logic/TaskService.java, src/main/java/com/bogdatech/utils/PlaceholderUtils.java
1, 修改新app的提示词
2，修改返回给前端的数据，保留4位小数
3，在定时任务的时候，检查是否存在Usage表的数据，不存在插入一条
=> 1, 修改新app的提示词 2，修改返回给前端的数据，保留4位小数 3，在定时任务的时候，检查是否存在Usage表的数据，不存在插入一条

src/main/java/com/bogdatech/task/GenerateDbTask.java
=> 1, 生成成功邮件，返回剩余字符数

src/main/java/com/bogdatech/controller/TranslateController.java
1，修改clickTranslation的传值
2，添加一些打印
=> 1，修改clickTranslation的传值 2，添加一些打印

src/main/java/com/bogdatech/Service/ITranslatesService.java, src/main/java/com/bogdatech/Service/impl/TranslatesServiceImpl.java, src/main/java/com/bogdatech/controller/TranslateController.java
=> 1，修改之前的主任务的状态

src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/entity/VO/TranslateArrayVO.java, src/main/java/com/bogdatech/logic/RabbitMqTranslateService.java
1，在生成任务前就修改任务状态
2，修改readTranslateDOByArray方法，添加一个boolean参数用户前端判断是否继续调用
=> 1，在生成任务前就修改任务状态 2，修改readTranslateDOByArray方法，添加一个boolean参数用户前端判断是否继续调用

src/main/java/com/bogdatech/controller/TranslateController.java
=> 1, 将获取方法改为取为list

src/main/java/com/bogdatech/controller/TranslateController.java
1, 修改getTranslateDOByShopNameAndSource方法，返回所有的状态为2的数据
=> 1, 修改getTranslateDOByShopNameAndSource方法，返回所有的状态为2的数据

src/main/java/com/bogdatech/controller/TranslateController.java
1,还是修改getTranslateDOByShopNameAndSource接口，当list为空时调用最新的
=> 1,还是修改getTranslateDOByShopNameAndSource接口，当list为空时调用最新的

src/main/java/com/bogdatech/logic/RabbitMqTranslateService.java, src/main/java/com/bogdatech/logic/TencentEmailService.java, src/main/java/com/bogdatech/utils/ResourceTypeUtils.java
=> 1,修改翻译失败发送的邮件

src/main/java/com/bogdatech/controller/TranslateController.java
=> 1, 对语言检验，超过5个报错

src/main/java/com/bogdatech/integration/PrivateIntegration.java
1,解析openai的返回数据，将totalToken存到数据库表格里面
=> 1,解析openai的返回数据，将totalToken存到数据库表格里面

src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/controller/UserPrivateTranslateController.java, src/main/java/com/bogdatech/entity/VO/TestPrivateModelVO.java, src/main/java/com/bogdatech/logic/UserPrivateTranslateService.java
=> 1,实现测试接口 2，给前端一个打印接口

src/main/java/com/bogdatech/logic/TranslateService.java
1,实现测试接口 2，给前端一个打印接口 3,修改最大线程数
=> 1,实现测试接口 2，给前端一个打印接口 3,修改最大线程数

src/main/java/com/bogdatech/integration/PrivateIntegration.java
=> 1, 在私有key openai里面做打印信息

src/main/java/com/bogdatech/integration/PrivateIntegration.java, src/main/java/com/bogdatech/logic/PrivateKeyService.java
=> 1, 修改翻译状态 2， 添加翻译标志

src/main/java/com/bogdatech/controller/CharsOrdersController.java, src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/controller/TranslationCounterController.java, src/main/java/com/bogdatech/entity/VO/TranslationCharsVO.java, src/main/java/com/bogdatech/exception/UserHandleException.java, src/main/java/com/bogdatech/logic/AILanguagePackService.java, src/main/java/com/bogdatech/logic/OrderService.java, src/main/java/com/bogdatech/logic/RabbitMqTranslateService.java, src/main/java/com/bogdatech/logic/TaskService.java, src/main/java/com/bogdatech/logic/TranslationCounterService.java, src/main/java/com/bogdatech/model/controller/request/CloudInsertRequest.java, src/main/java/com/bogdatech/requestBody/ShopifyRequestBody.java, src/main/java/com/bogdatech/utils/ShopifyUtils.java
1，查询是否是免费试用计划用户 
2，后端进行判断是否添加额度 
3，提供一个gid的获取方法
=> 1，查询是否是免费试用计划用户 2，后端进行判断是否添加额度  3，提供一个gid的获取方法

src/main/java/com/bogdatech/entity/DO/TranslateResourceDTO.java
=> 1，修改主题两个模块不翻译

src/main/java/com/bogdatech/controller/TranslateController.java
=> 1，按update降序排序

src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/model/service/RabbitMqTranslateConsumerService.java
=> 1，在发送邮件后，将userTranslate的状态改为2

src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/model/service/RabbitMqTranslateConsumerService.java
1,修改进度条，一条语言翻译后，状态一直卡在插入翻译数据状态
=> 1,修改进度条，一条语言翻译后，状态一直卡在插入翻译数据状态

src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/entity/DO/TranslateResourceDTO.java
1，ONLINE_STORE_THEME_SETTINGS_CATEGORY和EMAIL也不翻译了
=> 1，ONLINE_STORE_THEME_SETTINGS_CATEGORY和EMAIL也不翻译了

src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/entity/DO/TranslateResourceDTO.java, src/main/java/com/bogdatech/logic/RabbitMqTranslateService.java, src/main/java/com/bogdatech/model/service/RabbitMqTranslateConsumerService.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java
1，将translateAndCount方法改成translateByModel，防止handle出现问题
=> 1，将translateAndCount方法改成translateByModel，防止handle出现问题

src/main/java/com/bogdatech/logic/RabbitMqTranslateService.java
=> 1，修改后面发生失败的邮件消耗字数。

src/main/java/com/bogdatech/logic/RabbitMqTranslateService.java, src/main/java/com/bogdatech/logic/TaskService.java
=> 1，重新获取用户数据

src/main/java/com/bogdatech/logic/RabbitMqTranslateService.java, src/main/java/com/bogdatech/logic/TaskService.java, src/main/java/com/bogdatech/logic/TencentEmailService.java
=> 1，用户翻译成功和失败邮件

pom.xml, src/main/java/com/bogdatech/integration/EmailIntegration.java, src/main/java/com/bogdatech/logic/RabbitMqTranslateService.java, src/main/java/com/bogdatech/logic/TaskService.java, src/main/java/com/bogdatech/logic/TencentEmailService.java
=> 1，用户翻译成功和失败邮件 2，修改相关打印信息

src/main/java/com/bogdatech/logic/TranslationCounterService.java, src/main/java/com/bogdatech/logic/UserService.java
=> 1,免费试用直接加额度 2,卸载减额度

src/main/java/com/bogdatech/logic/TranslationCounterService.java
=> 1,免费试用直接加额度, 对免费试用进行判断，是修改免费试用状态为true，不是，存入相关数据

src/main/java/com/bogdatech/logic/OrderService.java, src/main/java/com/bogdatech/logic/TranslationCounterService.java, src/main/java/com/bogdatech/logic/UserService.java, src/main/java/com/bogdatech/utils/ResourceTypeUtils.java
1,免费试用直接加额度, 对免费试用进行判断，是修改免费试用状态为true，不是，存入相关数据
2,卸载后只减免费试用额度
3,免费试用不发邮件
=> 1,免费试用直接加额度, 对免费试用进行判断，是修改免费试用状态为true，不是，存入相关数据 2,卸载后只减免费试用额度 3,免费试用不发邮件

src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/integration/ArkTranslateIntegration.java, src/main/java/com/bogdatech/integration/ChatGptIntegration.java, src/main/java/com/bogdatech/integration/DeepLIntegration.java, src/main/java/com/bogdatech/integration/HunYuanIntegration.java, src/main/java/com/bogdatech/integration/PrivateIntegration.java, src/main/java/com/bogdatech/integration/ShopifyHttpIntegration.java, src/main/java/com/bogdatech/logic/RabbitMqTranslateService.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TaskService.java, src/main/java/com/bogdatech/logic/TencentEmailService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/model/service/RabbitMqTranslateConsumerService.java, src/main/java/com/bogdatech/task/RabbitMqTask.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java
=> 1,修改翻译逻辑的相关打印

src/main/java/com/bogdatech/integration/PrivateIntegration.java, src/main/java/com/bogdatech/logic/RabbitMqTranslateService.java, src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java
1,修改HTML翻译逻辑的bug，判断HTML部分文本后面是否有空格
=> 1,修改HTML翻译逻辑的bug，判断HTML部分文本后面是否有空格

src/main/java/com/bogdatech/controller/ShopifyController.java, src/main/java/com/bogdatech/logic/ShopifyService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/ProgressBarUtils.java
1,修改getProgressData的逻辑，如果获取不到任务数，改为从静态数据获取用户正在的翻译模块，返回对应数据
=> 1,修改getProgressData的逻辑，如果获取不到任务数，改为从静态数据获取用户正在的翻译模块，返回对应数据

src/main/java/com/bogdatech/constants/MailChimpConstants.java, src/main/java/com/bogdatech/logic/OrderService.java, src/main/java/com/bogdatech/logic/PrivateKeyService.java, src/main/java/com/bogdatech/utils/ProgressBarUtils.java
1,修改getProgressData的返回值，私有key数据为递减
2，添加免费试用的邮件
3，修改私有key的2个报错信息
=> 1,修改getProgressData的返回值，私有key数据为递减 2，添加免费试用的邮件 3，修改私有key的2个报错信息

src/main/java/com/bogdatech/logic/PrivateKeyService.java
=> 1,修改私有key部分翻译为5

src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/integration/ArkTranslateIntegration.java, src/main/java/com/bogdatech/integration/ChatGptIntegration.java, src/main/java/com/bogdatech/integration/DeepLIntegration.java, src/main/java/com/bogdatech/integration/HunYuanIntegration.java, src/main/java/com/bogdatech/integration/PrivateIntegration.java, src/main/java/com/bogdatech/integration/TranslateApiIntegration.java
=> 1, 添加报错后的打印日志

src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/integration/ALiYunTranslateIntegration.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java
=> 1, 修改一下打印日志

src/main/java/com/bogdatech/Service/impl/TranslationCounterServiceImpl.java, src/main/java/com/bogdatech/Service/impl/UserTrialsServiceImpl.java, src/main/java/com/bogdatech/controller/UserTrialsController.java, src/main/java/com/bogdatech/logic/UserTrialsService.java, src/main/java/com/bogdatech/requestBody/ShopifyRequestBody.java
1, 修改isOpenFreePlan方法的判断逻辑，当返回null时，返回success为false；当有值时，返回用户是否第一次免费试用
2，修改getSingleQuery的数据，少加了\" \"
=> 修改isOpenFreePlan判断逻辑和修改getSingleQuery数据

src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/controller/UserPicturesController.java, src/main/java/com/bogdatech/entity/DTO/SimpleMultipartFileDTO.java, src/main/java/com/bogdatech/integration/HunYuanBucketIntegration.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/utils/StringUtils.java
1, 将前端传的图片url，以MultipartFile格式文件存到腾讯云bucket中
2, 修改一些接口参数
=> 1, 将前端传的图片url，以MultipartFile格式文件存到腾讯云bucket中

src/main/java/com/bogdatech/integration/HunYuanBucketIntegration.java, src/main/java/com/bogdatech/utils/StringUtils.java
=> 1, 修改图片url的命名方式：8位随机数

src/main/java/com/bogdatech/controller/TestController.java, src/main/java/com/bogdatech/controller/TranslateController.java, src/main/java/com/bogdatech/integration/RedisIntegration.java, src/main/java/com/bogdatech/logic/PrivateKeyService.java, src/main/java/com/bogdatech/logic/RabbitMqTranslateService.java, src/main/java/com/bogdatech/logic/RedisProcessService.java, src/main/java/com/bogdatech/logic/TranslateService.java, src/main/java/com/bogdatech/task/RateTask.java, src/main/java/com/bogdatech/utils/AESUtils.java, src/main/java/com/bogdatech/utils/JsoupUtils.java, src/main/java/com/bogdatech/utils/LiquidHtmlTranslatorUtils.java, src/main/java/com/bogdatech/utils/RedisKeyUtils.java
1，用redis重新实现下缓存翻译
2，用md5对source做加密，为key的一部分
3, 每次读取缓存数据后后，重新计算时间（14天）
=> 用redis重新实现下缓存翻译

src/main/java/com/bogdatech/utils/JsoupUtils.java
=> 1, 放弃混元，用千问
